ImageCaption: Add an explicit type
Without it - only on Android - we get the following error -

The following NoSuchMethodError was thrown building LayoutBuilder:
I/flutter ( 4269): Class '_LayoutBuilderElement<BoxConstraints>' has no instance method 'watch'.
I/flutter ( 4269): Receiver: Instance of '_LayoutBuilderElement<BoxConstraints>'
I/flutter ( 4269): Tried calling: watch<MarkdownRendererConfig>()

This makes no sense to me, but it fixes it. So so strange.

Cause this code works when running the app on macos.